apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: on-call-schedule
  namespace: cronjobs
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: cronjobs/on-call-schedule
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: saas-secrets-eks
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
